%% FUNCTION FOR UPDATING EIGENVALUES (GOLUB)
%% NOTE THAT THE ORDER OF MU GENERATED BY GOLUB AND DIRECT DONOT MATCH

% function mu = eigenValues(lambda,rho1,a_bar)
% syms x
% eqn = vpa(  1 + rho1 * sum(a_bar.^2 ./ (lambda - x))== 0);
% mu = sort(double(solve(eqn)),'descend');
% end
function mu = s_eigenValues(lambda1,rho1,a_bar)
 try
    a_bar(isnan(a_bar)) = 0;
    syms x
    eqn = 1 + (rho1 * sum((a_bar.^2) ./ (lambda1 - x)));
%     mu1 = sort(double(solve(eqn)),'descend');
    mu1 = double(solve(eqn)); %don't sort
    %isreal(a_bar)
    if(~isempty(find(~real(a_bar))))
        mu = lambda1;
        non_zero_index = find(a_bar); % non - zero index
        j = 1;
        for i = 1:length(non_zero_index)
            mu(non_zero_index(i)) = mu1(j);
            j = j + 1;
        end
    else
        mu = mu1;
    end
 catch
     eqn1 = eqn
%     mu = lambda1
 end
end